- Cargo.lock
- Cargo.toml
- src/main.rs
- src/updater.rs
Right now I'm trying to follow the caching conventions used by the node client (main directory ~/.tldr/cache`, containing `LICENSE.md` and the `pages/` directory).
The problem is that this convention is not written down anywhere. If the two clients make different decisions, we could end up overwriting the cache of each other.
I thought about proposing a standard, but in the end it's probably the easiest if we simply dump the git export into our own cache (following the XDG standard at `~/.cache/tldr-rs` for POSIX systems). We could either dump the files into that directory directly, or alternatively put them into a `checkout` subdir.
The huge advantage of this is that we can scrap the `index.json` file [which is unreliable](https://github.com/tldr-pages/tldr/issues/487) and get rid of a …
> Rething caching

- src/formatter.rs
Right now, tar output looks like this:
```
- create a gzipped archive
tar czf {{target.tar.gz}} {{file1 file2 file3}}
```
> Support {{ }} syntax in formatter

- README.md
I went ahead and added some badges for Coveralls and Crates.io so that users can easily visit the crate page or code coverage status.
> Add badges for Coveralls and Crates.io

- Cargo.lock
- Cargo.toml
- src/cache.rs
- src/error.rs
- src/formatter.rs
- src/main.rs
- src/tokenizer.rs
Pretty small PR that closes #10.
I believe this PR also fixes a bug you might not of noticed, where if a user changed `$XDG_CACHE_HOME`, tealdeer would still create the cache under `~/.cache`. Correct me if I'm wrong though.
I've also gone through and removed the spaces like [you said](https://github.com/dbrgn/tealdeer/issues/10#issuecomment-211429317).
> Use rust-xdg for cache creation

- src/main.rs
Since macOS is also a BSD under the hood, this will probably yield better results.
> OS detection: Treat BSDs as "osx"

- README.md
My PR for packaging tealdeer on void was merged, so you can now easily install tealdeer on void: https://github.com/void-linux/void-packages/pull/4908
> Mention Void Linux Package in the README

- src/cache.rs
> Add (back) support for proxies

- .gitattributes
- Cargo.lock
- Cargo.toml
- README.md
- bash_tealdeer
- fish_tealdeer
- src/cache.rs
- src/config.rs
- src/main.rs
- src/types.rs
- tests/lib.rs
> Windows support

- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/main.rs
- tests/config.toml
- tests/lib.rs
I just added the [pager crate](https://crates.io/crates/pager) and a flag (`-p --pager`) to enable or disable it.
BTW, I have tested it with Rust 1.28.0 and it works well, maybe you can update.
I would need help for windows and macOS testers.
refs #36
> #36 add -p --pager flag to page the output using pager crate

- fish_tealdeer
It seems like this was broken on my machine (OSX, 10.14.6) when using the completions. It would strip the `, ` but it would not add a proper newline. Instead it added nothing. So it just become a giant single line. Basically, it didn’t work.
With this change, the string gets split properly. Since this is fish shell, the `string replace` command is guaranteed to be there.
> Use `string replace` instead of `sed`

- README.md
- src/config.rs
- src/formatter.rs
- tests/config.toml
This adds a config option to suppress empty lines in the output.
Closes #88.
> Add compact output option

- src/main.rs
- tests/lib.rs
This makes it display in yellow (instead of red) as it's more of a *warning* message than an *error* message.
> Tweak the outdated cache warning message

- README.md
- bash_tealdeer
- fish_tealdeer
- src/main.rs
- tests/lib.rs
- tests/tar-markdown.expected
- zsh_tealdeer
This is useful for when you want to open it up in a pager which doesn't
support ansi escape codes by default. In my use case it allows me to
open it inside vim without having to use an addon to convert ansi escape
codes to colours.
> Add -m / --markdown option for raw rendering

- tests/tar-markdown.expected
It broke because the `tar` tldr page was changed upstream :)
> Fix integration test

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/cache.rs
- src/main.rs
This includes a reqwest upgrade, which reduces the full dependency tree from 333 to 188 entries, mostly because some reqwest features (like cookies and compression) were disabled :slightly_smiling_face:
> Update dependencies, bump MSRV to 1.39

- src/main.rs
- tests/lib.rs
**TL;DR** make commands list display write one item per line instead of comma-separated items.
Tealdeer currently displays command list comma-separated, _e.g._
```sh
$ tldr --list
bar, baz, foo, qux
```
Whereas the [official TLDR specification](https://github.com/tldr-pages/tldr/blob/master/CLIENT-SPECIFICATION.md#arguments) states the following
> Additional decoration MAY be printed if the standard output is a TTY. If not, then the output MUST not contain any additional decorations. For example a page list MUST be formatted with 1 page name per line (to enable easy manipulation using standard CLI tools such as grep etc.).
_e.g._
```sh
$ tldr --list
bar
baz
foo
qux
```
Adding TTY-specific decorated output goes against [KISS principle](https://www.google.com/search?q=kiss+principle&oq=kiss+ …
> Make list option display comply with official spec

- tests/lib.rs
These methods might be useful in the future, so I don't want to remove them even if they're unused. The warnings clutter diffs in CI though.
> Tests: Allow dead code for feature selection

- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/main.rs
- tests/config.toml
- tests/lib.rs
This PR implements automatic updates of the cache.
This behavior is disabled by default and can be enabled in `config.toml`:
```toml
[updates]
auto_update = true
auto_update_interval_hours = 720
```
Fixes #90
Fixes #78
> Implement automatic cache updates

- Cargo.lock
- Cargo.toml
- bash_tealdeer
- fish_tealdeer
- src/main.rs
- src/types.rs
- tests/inkscape-default-no-color.expected
- tests/lib.rs
- zsh_tealdeer
Hello, first time hacking at this codebase.
So the aim of this pull request is to address the issues mentioned in #81. This was done by adding in a command line flag `--color` with the options `always, auto, never`.
Will use styling as long as ANSI support is detected.
Will use color _unless_:
* ANSI support isn't detected.
* The `NO_COLOR` environment variable exists as is the spec listed on the [`NO_COLOR` website](https://no-color.org/).
* The output isn't `stdout` (e.g. when the output is being piped to another program like `tldr man | xclip -sel clip`). This is done with the help of the newly added `atty` lib since it promises cross platform detection for such cases.
Disables colored output entirely.
* There was the case where the stale cache message attempted to be colored …
> Better color detection

- README.md
- src/config.rs
Closes #147
Allows defining colors as ANSI codes or RGB in `config.toml` e.g.:
```
[style.command_name]
background = { ansi = 7 }
foreground =  { rgb = { r = 255, g = 51, b = 255 } }
```
> Add support for ANSI code and RGB colors

- Cargo.lock
- Cargo.toml
> Remove xdg dependency

- tests/tar-markdown.expected
Build tests failing because tldr-pages repository changed file
https://github.com/tldr-pages/tldr/blob/master/pages/common/tar.md
and so test was failing, as the file the test compared to was not the version pulled from the archive.
Could attempt to generate this automatically in future?
Not very familiar with pull requests, so please let me know what would be helpful in future.
> tar markdown rendering test fixed

- .github/workflows/ci.yml
- src/cache.rs
- src/dedup.rs
- src/main.rs
After #125, I used the occasion to dig out valgrind and kcachegrind to do some performance optimization (something that's fun, but that I do way too seldom...)
To profile, I created a new standalone binary that included nothing but `get_languages` and this `main`:
```rust
fn main() {
get_languages(Some("en_US.utf8".to_string()), Some("de:en:fr".to_string()));
}
```
I then built in release mode and counted the instructions for `main` (since the function call to `get_languages` was inlined).
Results (in CPU instructions and percentage reduced compared to previous version):
- Initial: 6939 (100%)
- Replace `HashSet` for deduplication with linear search based approach: 4801 (-31%)
- Do not allocate `language` variable: 4796 (-0.1%)
- Avoid processing fallback language by inserting it directly …
> Language support improvements

- src/formatter.rs
- tests/config.toml
- tests/inkscape-default-no-color.expected
- tests/inkscape-default.expected
- tests/inkscape-v1.md
- tests/inkscape-v2.md
- tests/inkscape-with-config.expected
- tests/lib.rs
In my styling configuration, command names are printed boldly. With that, one part of the TL;DR page for the command `make` looks like:
You clearly see the "make" in the command line argument `--always-make` printed boldly too. I guess this shouldn't be the case. This fix makes sure that only command names with a preceding whitespace character are considered, which leads to:
> Consider only standalone command names for styling

- .github/workflows/ci.yml
- bash_tealdeer
- docs/src/config.md
- fish_tealdeer
- src/cache.rs
- src/config.rs
- src/main.rs
- src/types.rs
- src/usage.docopt
- tests/lib.rs
- zsh_tealdeer
The command prints out the different directories (config, cache, etc) used by tealdeer, and the reason why this directory path was chosen.
```
$ ./tldr --show-paths
Config dir:  /home/danilo/.config/tealdeer/ (OS convention)
Config path: /home/danilo/.config/tealdeer/config.toml
Cache dir:   /mnt/data/Caches/.cache/tealdeer/ (OS convention)
Pages dir:   /mnt/data/Caches/.cache/tealdeer/tldr-master/
```
```
$ TEALDEER_CONFIG_DIR=/tmp/conf ./tldr --show-paths
Config dir:  /tmp/conf/ (env variable)
Config path: /tmp/conf/config.toml
Cache dir:   /mnt/data/Caches/.cache/tealdeer/ (OS convention)
Pages dir:   /mnt/data/Caches/.cache/tealdeer/tldr-master/
```
CC @niklasmohrin
> Implement new --show-dirs command

- zsh_tealdeer
Changes information:
- Use array `commands=(...)` and `_describe` to deal with '[.md' & empty cache scenario.  Fixes #166
- Hide `tldr --list` stderr (`2>/dev/null`) which breaks completion with empty cache
- Remove `sed` since #112 changed commas to newlines
- Add new `sed`-equivalent replacement (`:` -> `\:`) using native [ZSH `${name//pattern/repl}`](http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion) since colon is special character in ZSH completions
- Add basic support for `-L, --language` flag from #125. In future, can consider adding extra completions maybe based on caches `pages.{lang}` folders.
- Remove extraneous completion of file names for positional arguments (i.e. `'*:file:_files'`)
The following are output from ZSH 5.8 with locally built master …
> zsh-completion: fix issue with [.md, add basic -L completion, remove extra _files args

- src/main.rs
- tests/lib.rs
Cargo.toml specifies Rust Edition 2018 which does not require 'extern crate' anymore.
> Remove 'extern crate' declarations

- src/config.rs
```
warning: derive helper attribute is used before it is introduced
--> src/config.rs:27:3
|
27 | #[serde(rename_all = "lowercase")]
|   ^^^^^
28 | #[derive(Copy, Clone, Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
|                              --------- the attribute is introduced here
|
= note: `#[warn(legacy_derive_helpers)]` on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #79202 <https://github.com/rust-lang/rust/issues/79202>
```
> fix check warn

- src/cache.rs
- tests/inkscape-patched-no-color.expected
- tests/inkscape-v2.patch
- tests/lib.rs
PR for Issue: #180 
Adds tests that should have been added in PR #182 
Added
- 3 integration tests for custom pages, including a 2 new markdown files for testing
- renamed my poorly named variable when I came across it again
- Unit tests for PageLookupResult
- Some new helper functions for the TestEnv struct for integration tests
> Tests for PR #142

- src/main.rs
- tests/lib.rs
Adresses #169. 
- Send logging messages to stderr instead of stdout so pagers do not intercept them.
- Updated tests to match these changes.
- Changed test_markdown_rendering to no longer rely on the tldr pages
repo. Instead manually adding a known page to use in this test,
because it failed due to the tldr pages repo updating this command (so
it no longer matched our expected output, which shouldn't cause our
tests to fail).
> Send all progress logging messages to stderr.

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/formatter.rs
- src/main.rs
- Use unbuffered IO for faster printing, see https://llogiq.github.io/2017/06/01/perf-pitfalls.html for more
- Use statically linked `rustls` over dynamically linked `openssl`.
Compared to the benchmark in #129 from the first post (ran `hyperfine --prepare 'sync; echo 3 | sudo tee /proc/sys/vm/drop_caches' './target/release/tldr tar'`). I don't know the exact command that the author of `outfieldr` ran, but you can also see a comparison I posted there. 
```
Benchmark #1: ./target/release/tldr tar
Time (mean ± σ):      29.3 ms ±   6.2 ms    [User: 1.7 ms, System: 4.3 ms]
Range (min … max):    24.3 ms …  50.1 ms    22 runs
```
> Use unbuffered I/O for faster printing to stdout, switch to Rustls

- docs/src/installing.md
These packages have been removed from AUR, only `tealdeer-git` exists now.
404ing pages:
https://aur.archlinux.org/pkgbase/tealdeer/
https://aur.archlinux.org/pkgbase/tealdeer-bin/
> Remove aur links for `tealdeer` and `tealdeer-bin`

- README.md
- benchmarks/Dockerfile
Closes #129
I started putting together a Dockerfile that gets all the clients and benches them with hyperfine. I decided to do it all in Docker, because I would not want to have all the clients on my system and to make it accessible for third parties to easily verify the results that our benchmarks produce.
At the time of writing, only tealdeer and the C client are compared, but I will add more clients.
Eventually, we could think about running benchmarks in CI, but this is not the focus of this PR.
> Hyperfine benchmarks

- src/config.rs
- tests/config.toml
- tests/inkscape-with-config.expected
Adds a configuration option for displaying information with the italics style. 
Fixes #146 
Before: 
After (configured example_variable to use italic instead of underline):
> Implement support for italics

- src/cache.rs
- tests/lib.rs
This PR tries to resolve #167. If `TEALDEER_CACHE_DIR` is set but does not exist, the complete path is just created as suggested in the issue. The user will be informed about the creation.
> Create cache directory path if it does not exist

- bash_tealdeer
- docs/src/usage.txt
- fish_tealdeer
- src/cache.rs
- src/main.rs
- src/types.rs
- tests/lib.rs
- zsh_tealdeer
This makes it compliant with the client spec (see #209).
The `-p` flag was previously used for the pager, using the pager now requires using the long flag (`--pager`). Alternatively the pager can be configured through the config file.
> Rename `-o / --os` to `-p / --platform`

- src/main.rs
- tests/lib.rs
This adds another allocation that wasn't necessary before, but the overhead is totally negligible.
Part of #209.
> Lowercase page names before lookup

- bash_tealdeer
- docs/src/usage.txt
- fish_tealdeer
- src/main.rs
- src/types.rs
- zsh_tealdeer
The Apple computer operating system was renamed from "OS X" to "macOS" in 2016. We should accept "macos" in addition to "osx" in all our CLI APIs, and the docs should also mention this alias instead of "osx".
For backwards compatibility and for compatibility with the tldr client specification, we should still accept "osx" though.
> Add "macos" alias for "osx"

- src/main.rs
- tests/lib.rs
This allows to say "this command line parameter requires either a command or a raw file".
Fixes #219.
(Clap is pretty awesome!)
> Introduce command_or_file arg group

- src/config.rs
- src/main.rs
- tests/lib.rs
A simpler version of #184 that doesn't change the config structure or file lookup logic.
Fixes #182.
> Custom pages in show paths

- docs/src/SUMMARY.md
- docs/src/usage_custom_pages.md
- src/cache.rs
- src/main.rs
- src/output.rs
- tests/inkscape-v2.patch
This way a patch file does not need a well-formed header anymore.
Fixes #181 and thus the last open feature/bug issue for the 1.5.0 milestone! 🎉
Replaces #202.
> Concatenate page and patch bytes before processing

- src/cache.rs
Apparently `Client::new` can panic (see #244), so let's return the error instead.
> Cache: Return error if HTTP client cannot be created

- src/main.rs
- src/output.rs
> Move pager configuration near render logic

- src/cache.rs
With this fix, when an invalid ZIP is downloaded:
```
Error: Could not update cache
Caused by:
0: Could not decompress downloaded ZIP archive
1: invalid Zip archive
```
When a non-successful HTTP error status is returned:
```
Error: Could not update cache
Caused by:
0: Could not download tldr pages from https://tldr.sh/assets/tldr.zap
1: HTTP status client error (404 Not Found) for url (https://tldr.sh/assets/tldr.zap)
```
Anyhow is awesome 🙂
Fixes #252.
> Handle cache download errors

- completion/bash_tealdeer
- completion/fish_tealdeer
- completion/zsh_tealdeer
- docs/src/usage.txt
- src/cli.rs
- src/main.rs
- Adding an empty `rustfmt.toml` enforces default formatter settings regardless of user's global settings
- See https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#configuring-rustfmt
- Currently if the user enables auto update in the config file, there is no way to temporarily disable it via CLI
- This is a problem when for example, the network is not available or is very slow. The client simply errors and refuses to display anything, despite the fact that the cache may be perfectly good (albeit a little old)
- Adding `no-auto-update` flag allows the client to stay usable in such situations
I will need some help with the completion scripts since I have no experience with these.
> Add `no-auto-update` flag

- src/main.rs
- tests/lib.rs
Output:
Fixes #250.
@niklasmohrin @uhthomas what do you think?
> Add note about auto-updates when cache is missing

- completion/bash_tealdeer
- completion/fish_tealdeer
- completion/zsh_tealdeer
- docs/src/usage.txt
- src/cache.rs
- src/cli.rs
- src/types.rs
`tldr` added android-specific commands under a new 'android' platform last year: <https://github.com/tldr-pages/tldr/issues/5462>
I think I caught all uses of the platform types, but another pair of eyes would be much appreciated!
> Add support for android platform

- src/cache.rs
- src/main.rs
- tests/lib.rs
Fix #205 
I have added custom pages to the output of list by reading from the `custom_pages_dir` from the config and walking that directory for any pages. This also includes custom pages in the autocompletion.
This is my first contribution, so please let me know if something has to be changed or added :innocent:
> Add custom pages to list output

- Cargo.lock
- Cargo.toml
- docs/src/config_style.md
- src/config.rs
- src/main.rs
- src/utils.rs
ansi_term is not actively maintained anymore (see https://rustsec.org/advisories/RUSTSEC-2021-0139). Replace it with a suitable alternative.
I looked at termcolor, owo-colors and yansi, and ended up picking yansi:
- It is very simple
- It does not do terminal color support checking (we already do that in tealdeer)
- Its color enum type is almost identical to the one from ansi_term, so migrating is easy
- It's developed by Sergio Benitez (of Rocket fame)
The only change from a config API point of view is that "purple" is now renamed to "magenta", but "purple" still works.
(Based on #287, merge that one first!)
> Replace ansi_term

- docs/src/config_directories.md
- src/cache.rs
- src/config.rs
- src/main.rs
- src/types.rs
- tests/lib.rs
Based on #212. Thanks @hgaiser for the initial work!
- Config: Add `cache_dir` to `[directories]` section
- Deprecate old `TEALDEER_CACHE_DIR` env variable
- Introduce path source for `custom_pages_dir` as well
- Add integration test
- Update docs
Implementation notes:
- Logic to handle legacy env var, config override and default cache dir selection is now in the `Config::try_from(RawConfig)` impl
- Logic to determine `custom_pages_dir` is moved into `Config::try_from(RawConfig)` as well for consistency
The logic to determine which cache directory is used is now in `config.rs`, when converting the `RawConfig` to `Config`. I think this is the place where the config file and external factors (defaults, env vars, etc) can be taken into account to determine a final config.
> Allow overriding cache directory through config

- docs/src/usage.txt
- src/cli.rs
- src/main.rs
Three commands were deprecated in the last release of tealdeer (1.5.0, almost a year ago) and can be removed now:
- `--config-path` (use `--show-paths` instead)
- `-o / --os` (use `-p/--platform` instead)
- `-m / --markdown` (use `-r/--raw` instead)
> Remove deprecated commands

- src/config.rs
The two values were inverted 😂
I think when this is merged, I'll do an 1.6.1 release, since this bug can be a bit confusing to users.
> Fix path source for custom pages dir

- docs/src/installing.md
Adds scoop as a supported installation method for tealdeer in docs.
It is present in the `main` repository of scoop which is enabled by default. So the only step needed to install `tealdeer` from scoop is `scoop install tealdeer`.
> Add scoop package manager as supported installation method

- docs/src/installing.md
It was a no-break space (U+00A0, `&nbsp;`), which causes mdBook to ignore the line break and [render wrongly](https://dbrgn.github.io/tealdeer/installing.html#package-managers).
Instead, a regular space (U+0020) should be used.
- openSUSE: [tealdeer](https://software.opensuse.org/package/tealdeer?search_term=tealdeer) - Scoop: [tealdeer](https://github.com/ScoopInstaller/Main/blob/master/bucket/tealdeer.json)
- Solus: [tealdeer](https://packages.getsol.us/shannon/t/tealdeer/)
- openSUSE: [tealdeer](https://software.opensuse.org/package/tealdeer?search_term=tealdeer)
- Scoop: [tealdeer](https://github.com/ScoopInstaller/Main/blob/master/bucket/tealdeer.json)
- Solus: [tealdeer](https://packages.getsol.us/shannon/t/tealdeer/)
> Docs: Fix typo (irregular space → regular space)

- Cargo.lock
- Cargo.toml
- src/main.rs
Right now we only support building with Rustls. However, there are quite a few architectures that aren't yet supported by "ring" (the crypto library used by Rustls), for example MIPS, PowerPC or SPARC.
To offer an alternative, I added the "native-tls" feature that can be used instead of "native-roots". When used, the native TLS stack is used instead of Rustls (i.e. SChannel on Windows, Secure Transport on macOS and OpenSSL otherwise).
> Allow building with native-tls

- src/line_iterator.rs
@niklasmohrin 
As you mentioned in #314, I improved test functions on `LineIterator`.
With your counter example code:
```rust
let mut previous = 0;
if let Err(e) = Read::bytes(&mut self.reader)
.find(|b| {
let res = previous == b'\n';
previous = *b.as_ref().unwrap();
res
})
.transpose()
```
The test function will fail:
```
❯ cargo test test_first_line
Compiling tealdeer v1.6.1 (/home/potato/repos/tealdeer)
Finished test [unoptimized + debuginfo] target(s) in 2.76s
Running unittests src/main.rs (target/debug/deps/tldr-8d4cf65b28f436c9)
running 2 tests
test line_iterator::test::test_first_line_old_format ... ok
test line_iterator::test::test_first_line_new_format ... FAILED
failures:
---- line_iterator::test::test_first_line_new_format stdout ----
thread …
```
> Line iterator: Improve test functions

- completion/fish_tealdeer
See: #327 
I had fish installed and so implemented @niklasmohrin's suggestion.
Tested locally with:
- empty cache (it does the right thing and doesn't output the error text)
- `update`d cache (it does the right thing and still auto completes)
> Chore Guard Fish Completion When Cache Is Empty

- completion/bash_tealdeer
- completion/zsh_tealdeer
when tldr-pages doesnt exist (yet, as in, new installation), `tldr --list` will output something that makes no sense for the completions. I am not qualified to do a real fix, but the completions output did bug me enough to patch it for zsh and bash. I tried to patch it for fish as well but couldnt get the original completion to work so im leaving the problem for actual fish users. 
TL;DR:
Purpose: reduce annoyance during first use, which is important for user-friendliness
Method: patch completions with a simple if-no-error check, for zsh and bash.
> added checks for wrong `tldr --list` output in completions

- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
- Remove unmaintained rust actions and use the components directly in the [GitHub action runners](https://github.com/actions/runner-images).
- Update runners.
- Update toolchain to https://github.com/dtolnay/rust-toolchain.
- Bump the `actions/checkout` version to `v3` (Node 16).
- Bump the `actions/upload-artifact` version to `v3` (Node 16).
- Bump the `actions/download-artifact` version to `v3` (Node 16).
> Update CI workflows

- Cargo.toml
> Include `completion/*` in published crate

- docs/src/usage.txt
- src/cache.rs
- src/cli.rs
- src/main.rs
- tests/lib.rs
Fix for an old issue #45 - to allow specifying multiple `platform`s on the cli.
Behaviour is to try get the tldr page for each platform given - so if a page doesn't exist for one platform but does for another, you still get the page displayed.
> Allow querying multiple platforms

- README.md
The badge currently says "failing", although the latest commit on main passed CI. I changed the image to what Github generates if you click on the "Create status badge" button and the URL is slightly different, so maybe this is the reason?
> Update Github actions badge

- docs/src/installing.md
> Update Arch Linux package URL in installing.md

- .github/workflows/release.yml
First of all THANK YOU for all the work you put into `tealdeer` and this awesome open-source project in general ❤️ 
This PR adds support for the `linux/arm64` platform (which is required for i.e. Linux Docker images on Apple M1/M2/M3 Chips). 🚀 
I'd love to download the `linux/arm64` binary directly from releases in this repository in the future.
If possible please create a new release after merge.
I have tested the build process and binary release with a fictional `v1.6.2` release in my fork.
You can find the release here: [github.com/nifr/tealdeer/releases/tag/v1.6.2](https://github.com/nifr/tealdeer/releases/tag/v1.6.2)
Try it as follows:
```bash
docker run --rm -it --platform=linux/arm64 debian:bullseye-slim
curl -sL \
-o /usr/local/bin/tldr \ …
```
> feat: add release build target "linux-aarch64-musl" for platform "linux/arm64"

- .github/workflows/ci.yml
- Cargo.toml
For clap v4 (#298), we need a higher MSRV, currently at least Rust 1.64.
Our MSRV policy is:
> When publishing a tealdeer release, the Rust version required to build it should be stable for at least a month.
I'd suggest to jump to 1.75. It's the current stable, released on December 28, and contains the "async fn in traits" change which makes it a potential synchronization point for libraries.
> Bump MSRV to 1.75

- Cargo.toml
```
Benchmark 1: tldr ip
Time (mean ± σ):       2.9 ms ±   0.2 ms    [User: 1.0 ms, System: 1.6 ms]
Range (min … max):     2.0 ms …   3.6 ms    500 runs
Benchmark 2: ./target/release/tldr ip
Time (mean ± σ):       2.6 ms ±   0.2 ms    [User: 1.2 ms, System: 1.1 ms]
Range (min … max):     1.8 ms …   3.4 ms    500 runs
Summary
./target/release/tldr ip ran
1.15 ± 0.13 times faster than tldr ip
```
> performance optimize with cargo flags

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
- CHANGELOG.md
- completion/bash_tealdeer
- completion/fish_tealdeer
- completion/zsh_tealdeer
- docs/src/usage.txt
- src/cache.rs
- src/cli.rs
- src/types.rs
- This PR adds support for FreeBSD, NetBSD and OpenBSD platforms that we recently added upstream (I announced it as part of the 2.1 client specification release last year).
- ~This PR also adds support for querying the common platform via a dedicated flag for #323.~ (This didn't work during testing so will revert it)
- Bump `actions` from `v3` (Node 16) to `v4` (Node 20).
- Added GitHub dependabot configuration to automate these dependency updates for GitHub actions as well as Cargo (dependabot will create PRs monthly to update these dependencies).
- Fix spacing in the changelog.
For #349
> feat: add BSD platform support; chore: update workflows

- .github/workflows/gh-pages.yml
Small PR to implement the stop-gap solution discussed in Issue #358 (https://github.com/dbrgn/tealdeer/issues/358#issuecomment-2045967635)
Makes the gh-pages workflow run only on version tag push (i.e. release).
> Generate docs only upon release

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- docs/src/usage.txt
- src/cache.rs
- src/cli.rs
- src/main.rs
- src/types.rs
Again, this is a pretty big update with multiple breaking changes that requires changing how our argument parsing is set up. (If I ignore the effort to upgrade, this update does contain some nice API improvements, so I guess in the long term it's worth it. The blogpost [is an interesting read](https://epage.github.io/blog/2022/09/clap4/).)
Fixes #350.
> Migrate to Clap v4, bump MSRV to 1.75

- .github/workflows/ci.yml
- .github/workflows/gh-pages.yml
- .github/workflows/release.yml
Create release builds for Apple's ARM machines as well.
Fixes #365.
> CI: Create release builds for Apple silicon (ARM)

- Cargo.lock
- Cargo.toml
- src/main.rs
The `atty` crate is unmaintained, `std::io::IsTerminal` is stable since Rust 1.70.
> Replace `atty` with `std::io::IsTerminal`

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
- src/output.rs
- src/utils.rs
Release note: https://github.com/SergioBenitez/yansi/releases/tag/v1.0.0
It'd be nice to have a version bump for this (patch level suffices), so I can straight update it in Debian rather than having to carry a patch ;)
> Upgrade yansi: 0.5.1 -> 1.0.1

- Cargo.lock
None of the security alerts are relevant to tealdeer, but it doesn't hurt to update the lockfile.
> Update dependencies to hush dependabot

- src/config.rs
See #306. The joined path is not cleaned in any way, so the resulting paths will not be very pretty, but since Rust stdlib afaik does not give us anything built-in for cleaning paths without touching the filesystem, I leave the paths as they are.
> Resolve paths in config [directories] relative to the config directory (#306)

- docs/src/usage.txt
- src/cache.rs
- src/main.rs
- src/types.rs
- tests/lib.rs
> Add `common` platform to CLI

- docs/src/usage.txt
- src/cli.rs
- src/main.rs
- tests/lib.rs
Fix https://github.com/tealdeer-rs/tealdeer/issues/383
> Add args: `--edit-page` and `--edit-patch`

- tests/lib.rs
> Only create a single temporary directory in integration tests

- Cargo.lock
- Cargo.toml
- src/cache.rs
ureq is a blocking HTTP client. ureq is simpler than reqwest. This brings:
- smaller binary size
- cleaner configuration interfaces
Fixes #415
> Replace reqwest with ureq

- docs/src/usage.txt
- src/cache.rs
- src/cli.rs
- src/config.rs
- src/main.rs
- src/output.rs
- src/types.rs
- tests/lib.rs
Inspired by #141
Closes #107
Note: In the original PR, some modifications were made so that the path specified by the config file flag can be used as the output path of the seed-config option. I chose not to do that here for now, because I think the meaning of this usage wouldn't be visible and clear to the user. Let me know if you think otherwise.
> Add an option to specify a custom config file to be used

- docs/src/SUMMARY.md
- docs/src/config.md
- docs/src/config_search.md
- docs/src/config_updates.md
- src/cache.rs
- src/config.rs
- src/main.rs
- tests/lib.rs
Closes #251
Best reviewed commit by commit.
Test for the download_languages setting are just destined to be flaky if we update from the upstream repository. I would just test it by hand for now and defer automatic tests until we have #390.
>  Add `search.languages` and `updates.download_languages` settings
