Cargo.lock
Cargo.toml
src/formatter.rs
src/main.rs
src/updater.rs

- Implemented parsing and render / update commands.
- Moved formatter to separate module.

Argument Parsing with Docopt

---

Cargo.lock
Cargo.toml
src/main.rs
src/updater.rs

Check for last update of cache, warn if it's too old or missing.

Last update

---

src/cache.rs
src/error.rs
src/main.rs

With this, the "core" feature is finally implemented.

Render pages from cache

---

src/cache.rs
src/main.rs

Allows the user to delete the cache.

Implement --clear-cache flag

---

README.md
src/cache.rs
src/main.rs
src/types.rs

Implement --os

---

.editorconfig
.travis.yml
Cargo.lock
Cargo.toml
LICENSE-APACHE
LICENSE-MIT
README.md
src/formatter.rs
src/main.rs
src/tokenizer.rs
src/types.rs

Blogpost by @killercup: https://pascalhertleif.de/artikel/good-practices-for-writing-rust-libraries/

Implement Best Practices

---

src/cache.rs

For some reason, the cache was not actually being updated because the
`Archive.unpack()` method doesn't overwrite any files.
So now we clear the cache directory before unpacking the archive.
Fixes #18.

Fix cache updating

---

Cargo.lock
Cargo.toml

Update dependencies and replace tar-rs fork with upstream version.

Dependencies

---

src/cache.rs

Fix creation of cache dir

---

.travis.yml
README.md

Require Rust >=1.6

---

src/cache.rs
src/error.rs
src/main.rs
tests/lib.rs

Hopefully I didn't miss anything.

Rename everything named tldr to tealdeer

---

bash_tealdeer

To use bash completion: Rename 'bash_tealdeer' to 'tldr' and move it
to /usr/share/bash-completion/completions/ .

Add bash completion

---

README.md

(tested on NixOS. Not yet tested on other Nix-enabled Linux or on Nix-enabled macOS, but should work there, too, I hope.)

add Nix install instructions

---

.circleci/config.yml
src/main.rs

Also add the logging feature to CI, so that this doesn't happen again.

Fix logging initialization

---

README.md

There was too much content. Condense it.

README: Simplify package manager instructions

---

README.md
zsh_tealdeer

It's my first attempt at a zsh completion file. Let me know if some changes are needed.

Add zsh autocompletion

---

.github/workflows/ci.yml

Previously forked PRs were not tested.

CI: Run on pull requests

---

tests/tar-markdown.expected

The tar tldr page was updated.

Fix integration tests

---

src/main.rs
tests/lib.rs

Move cache age warning to stderr

---

tests/lib.rs

Add test for pager warnings on Windows

---

tests/tar-markdown.expected

Update outdated expected output for the markdown test

---

README.md

This may help people looking for a way to place their configuration file into a different directory.

Mention the environment variable TEALDEER_CONFIG_DIR in the README

---

zsh_tealdeer

Fix `zsh` completion for `--color` argument (#137)

---

docs/README.md
docs/src/config.md

Document location of cache directory

---

src/cache.rs
tests/lib.rs

The issue #82 is quite old, even though it already mentions the line to fix. Or is there something more to do here that I am missing?

Fix #82: Allow SunOS override

---

.github/workflows/ci.yml
README.md

Here's the updated policy, as discussed in #190.
Closes #190.

Update MSRV policy

---

README.md

Update @SShrike → @severen

---

src/cache.rs
src/config.rs
src/error.rs
src/formatter.rs
src/line_iterator.rs
src/main.rs
src/output.rs
tests/lib.rs

Initially I was sceptical, but by now I really like the tree-style imports.

Use tree-style imports

---

docs/src/installing.md

Hello 👋🏻,
I maintain the tealdeer package in Funtoo Linux, so I thought I might as well mention its existence in the docs :^)

chore: add funtoo package to list

---

src/config.rs
src/main.rs
src/utils.rs

These functions prepend a consistend prefix and they also use colors (when enabled).
Messages are written to stderr.

Add helper functions: print_warning / print_error

---

src/main.rs
zsh_tealdeer

I missed some occurrences in #217.

Remove last traces of short `-p` flag for the pager

---

src/cache.rs
src/config.rs
src/main.rs
src/output.rs
src/utils.rs
tests/lib.rs

I think this should fix the failing CI build

Fixed clippy lints for CI

---

CHANGELOG.md
README.md
docs/src/config.md
docs/src/config_style.md
docs/src/config_updates.md
docs/src/installing.md
docs/src/intro.md

Some leftovers, fixes and improvements.

Documentation fixes

---

docs/src/SUMMARY.md
docs/src/tips_and_tricks.md

This chapter can feature solutions to requests such as #334 and #340.

Add "Tips and Tricks" chapter to user manual

---

src/cache.rs
src/line_iterator.rs

Some new lints with Rust 1.80.

Make clippy happy

---

docs/src/usage.txt
src/cli.rs

- Rename PLATFORMS to PLATFORM
- Add hint about specifying platform multiple times
See https://github.com/dbrgn/tealdeer/pull/300#issuecomment-1925882814

Command line help: Add hint about platform overrides

---

tests/lib.rs

Add tests for osx/macos alias

---

src/main.rs

Currently, `main` uses `print_error` and `process::exit` in several places. These could be unified by propagating errors via `Result`s. There is one place left that manually calls `print_error`, because the error should be followed by help instructions printed without any highlighting.

Move most of `main` to `try_main`

---

.github/workflows/ci.yml
Cargo.toml

Bump MSRV to 1.80

---

src/cache.rs
src/cli.rs
src/formatter.rs
src/line_iterator.rs
src/main.rs
src/types.rs

Nightly used: 1.92.0-nightly (f2932725b 2025-09-24)

 Run `cargo +nightly clippy --fix` and formatting 
